---
- name: install and run the Lamp stack on ec2 on aws
  hosts: webservers
  remote_user: root
  become: yes
  tasks:
    - name: install Apache, PHP and MySql packages. 
      yum: 
        name:
          - httpd
          - php
          - php-mysql
        state: installed

    - name: Enabling and Starting the service httpd
      service:
        name: httpd
        enabled: yes
        state: started

    - name: Copying the tar file
      copy:
        src: /home/galileo/devops/html.tar.gz
        dest: /var/www/
        force: yes
    
    - name: unarchive
      unarchive:
        src: /var/www/html.tar.gz 
        dest: /var/www/
        remote_src: true

    - name: Confirm that 200 OK response is returned
      uri:
        url: "http://18.216.242.207"
        status_code: 200

    # - name: Enable the firewall port for Apache
    #   firewalld: 
    #     port: 80/tcp 
    #     permanent: true 
    #     state: enabled 
    #     immediate: yes


- name: install mysql
  hosts: database
  remote_user: root
  become: yes

  vars_files:
    - vars.yaml
  
  roles:
    - role: idealista.mysql_role
